# Generated by Django 5.1.5 on 2025-01-17 03:35

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries={
        "to do":"Issues to fix",
        "in progress":"Issues which are currently working on",
        "done":"Solved issues"
    }
    Status=apps.get_model("issues", "Status")
    for key, value in entries.items():
        status_obj=Status(name=key, description=value)
        status_obj.save()

def populate_priority_level(apps, schemaeditor):
    entries={
        "low":"It's a simple issue",
        "medium":"It has some importance",
        "high":"It's really important"
    }
    Priority=apps.get_model("issues", "PriorityLevel")
    for key, value in entries.items():
        priority_obj=Priority(name=key, description=value)
        priority_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial')
    ]

    operations = [
        migrations.RunPython(populate_status),
        migrations.RunPython(populate_priority_level),
    ]

