# Generated by Django 5.1.5 on 2025-01-17 01:49

from django.db import migrations

def populate_teams_and_roles(apps, schemaeditor):
    teams_entries={
        "Alpha":"The A team",
        "Bravo":"The B team",
        "Charlie":"The C team",
    }

    role_entries={
        "developer":"The person on the team who works on issues",
        "scrum master": "The team's coach",
        "product owner": "Team member in charge of defining product scope",
    }
    
    Team=apps.get_model("accounts", "Team")
    Role=apps.get_model("accounts", "Role")
    
    for key, value in teams_entries.items():
        team_obj=Team(name=key, description=value)
        team_obj.save()

    for key, value in role_entries.items():
        role_obj=Role(name=key, description=value)
        role_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_teams_and_roles),
    ]
